### PR TITLE
Add a supporting axle to the worm gear

### PR DESCRIPTION
**Pull request by awigen**
Also hollow out the frame to allow this axle

### CODE REVIEW

**Comment by tobbelobb** [comment]
Thank you for this! Do you have a plan on how to print it?

**Comment by tobbelobb** [comment]
I made it printable by making base grow by 45 deg. Also added some more set screws that I've missed having there. Merging.

**Comment by awigen** [comment]
Hi,

I printed it "upside down" compared to before, but the new design should 
be good as well.

https://owncloud.wigen.net/index.php/s/e9xgo50N8701FZm



Cheers,

Alex

**Comment by tobbelobb** [comment]
Cool! I thought the overhangs would be too much. I like your version better if it actually works.

I'm also interested if the corner will be strong enough to hang without the bottom_plate flexing.

**Pull request merged**
